# docker-compose.yml

version: '3.8'

services:
  # The Streamlit Application
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/app  # Mounts local 'app' folder into the container for live-reloading

  # The Redis State Store
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # The PostgreSQL Database
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: